rules:
  - name: Java
    win: java -version
    unix: java -version
    errorMessage: please install java version 11, 14, or 15
    match:
      - java version "11"
      - java version "15"
      - java version "14"
  - name: Python
    win: python --version
    unix: python --version
    errorMessage: please install python 3
    match:
      - Python 3\..*
  - name: Node
    win: node -v
    unix: node -v
    errorMessage: please install node v10 or above
    match:
      - v1.\.
