name: Deploy

# Run deployment to OSSRH
on:
  push:
    branches:
      - main
      - dev
      - 'release/*'

jobs:
  deploy-ossrh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn clean --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER}}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
