name: Environment test
on:
  push:
    branches:
      - integration-test
jobs:
  environment-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: mvn package
      - run: cp target/dx-voyager.jar target/test-classes/githubEnvironmentTest/dx-voyager.jar
      - run: java -jar dx-voyager.jar
        working-directory: target/test-classes/githubEnvironmentTest
      - uses: actions/upload-artifact@v2
        with:
          name: environment-test-data-container
          path: target/test-classes/githubEnvironmentTest/data-container.zip
          retention-days: 2
