name: Release Docs

on:
  push:
    branches:
      - docs

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install docs dependencies
        run: pip install mkdocs-material

      - name: Deploy docs to GitHub Pages
        run: mkdocs gh-deploy --force
